### ISSUE TITLE
File Format Does Not Exist

### ISSUE THREAD

**Issue by mihail911** [jacopotagliabue/you-dont-need-a-bigger-boat#6]
Hey there!

I was recently looking at the `remote_flow` workflow in the repo. However at the step where data needs to be uploaded into a Snowflake instance, I have been running into an error when calling `make upload`:
```
Traceback (most recent call last):
  File "push_data_to_sf.py", line 83, in <module>
    write_chunks(table=sku_to_content_table,
  File "push_data_to_sf.py", line 64, in write_chunks
    conn.upload_file(f"{output_prefix}*", table_name)
  File "/app/connectors/sf_connector.py", line 79, in upload_file
    self._cs.execute(f"COPY INTO {table} FILE_FORMAT = ESCAPED_DQ")
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 693, in execute
    Error.errorhandler_wrapper(
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 258, in errorhandler_wrapper
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/usr/local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 188, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002003 (02000): SQL compilation error:
File format 'ESCAPED_DQ' does not exist or not authorized.
```

It appears that `ESCAPED_DQ` might be a custom defined file format for Snowflake data ingestion? Where is its definition?

Thanks for putting this repo together!

**Comment by bigluck** [comment]
Ciao @mihail911, thanks for your feedback.
I've created a PR with the fix -> https://github.com/jacopotagliabue/you-dont-need-a-bigger-boat/pull/7

Can you test it? Thanks

**Comment by mihail911** [comment]
Thanks for the prompt response @bigluck. This LGTM.
